CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT ,
	TITLE VARCHAR(50) NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER  VARCHAR(50) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT  INT  DEFAULT 0,
	IMG VARCHAR(500),
	PRIMARY KEY(IDX)
);

CREATE TABLE MEMBER(
	ID VARCHAR(30) NOT NULL,
	PW VARCHAR(100) NOT NULL,
	NICK VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);
COMMIT;

--DROP TABLE BOARD;
select * from MEMBER;
delete FROM MEMBER;
DROP TABLE Member;

-- 최신
delete FROM BOARD where title = '';
    
SELECT @rownum := @rownum + 1 AS ROWNUM, b.* FROM (SELECT * FROM BOARD WHERE WRITER = 'ㄱㄱ' ORDER BY INDATE DESC LIMIT 1) b, (SELECT @rownum := 0) rownum;
SELECT * FROM MEMBER;